### ISSUE TITLE
Sorting tasks

### ISSUE THREAD

**Issue by afbora** [afbora/SimpleTimeTracker#8]
> Expansion is super!
>
> But very lacking is sorting by project. If possible, please add it!
> 
> Максим Климашевский

**Comment by mrCoder256** [comment]
Hello Ahmet!

I very like your tracker and I use it almost every day even for my home or regular tasks ^_^

Since today, if I'm not mistaken, an active task is moving to the top. Sometimes I have 2-3 active task at the same time (one big task contains other one, per instance). I turn off one task, then reset other one, then again turn on these two... And what I see now, active tasks constantly moving relative to each other, but it was very convenient for me that each task was in its place and did not move in previous versions.

Can you add, please, possibility to pin elements (to prevent moving active tasks) or add a setting to enable/disable active tasks moving?

P.S. Do you accept donations?))

P.P.S. I'm not sure if I wrote in the correct page/task/thread. I hope you will see my questions and respond.

**Comment by afbora** [comment]
Thank you @mrCoder256 Actually, the reason why it went to the top was because I couldn't see the actively used tasks without scroll down when they were at the bottom. I thought it would be more useful for users if the tasks that are currently actively used always stay at the top 🙂

Btw If you still want to donate, you can buy me a coffee [from here](https://market.owebstudio.com/checkout/buy/42165b00-93fe-4dad-aaaa-e8a8b9b7435a) (via own business account) 💛 I'll also put this donate link to the extension later versions.

**Comment by mrCoder256** [comment]
I hope you'll find some solution that will be useful for those who want to see active tasks at the top and those who got used to see all tasks in particular places 😇

Have a good coffee break 😉

**Comment by afbora** [comment]
Thank you so much 💛 I'm working on new release 🤞

**Comment by afbora** [comment]
Fixed in https://github.com/afbora/SimpleTimeTracker/pull/13, submitted chrome web store and will be available soon.

**Comment by mrCoder256** [comment]
Thank you very much!

**Comment by afbora** [comment]
@mrCoder256 My thanks! Did you like it? 
I'm open any "simple" ideas 🙏

**Comment by mrCoder256** [comment]
Yeah, I like the new version))

About new features. Actually, I have some ideas. Maybe, timers would be more beautiful and nice looking if they could be customized. At least, you can add settings for choosing a color of a highlighted (on mouse move) and running tasks (they are light blue and light green now). Plus, maybe, it will be useful to paint tasks (a row of table or just a color of text) of one project the same color. You know, some people are used to better perceive visual information. I mean it will be faster for them to read/find some timer by color not by text :)

The second idea is to add some statuses for a timer. For instance, the task may be "mandatory" and "finished". It may be implemented by adding two buttons (exclamation mark and check mark, for example). And now at the start of day I can prioritize my tasks for today by labeling them mandatory, and during the day I mark completed tasks as "finished".
But with this improvement the simple minimalistic time tracker may become slightly overloaded.

**Comment by afbora** [comment]
Thank you! Could you create separate issues for each idea please?
https://github.com/afbora/SimpleTimeTracker/issues/new/choose

**Comment by mrCoder256** [comment]
Done 😄
